---

#
#  Copyright 2013-2021 ASC
#
#  This file is part of "Οἰκουμένη" ("Ecumene") - set of applications and
#  configurations to assist with deploy and set up of an environments.
#
#  Οἰκουμένη is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation, either version 3 of
#  the License, or (at your option) any later version.
#
#  Οἰκουμένη is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Οἰκουμένη.
#  If not, see <http://www.gnu.org/licenses/>.
#
##


-   name:               Upload Ingress Controller Helm.
    synchronize:
        src:            "artifacts/{{ item }}"  # If this path is relative, then it's relative to Ansible control machine working directory (this is NOT relative to roles/*/files).
        dest:           "/tmp/artifacts/{{ item }}"
        rsync_opts:
            - "--copy-links"
            #- "--relative"  # It do not mean what do you think. 'man rsync' - This means that the full path names specified on the command line are sent to the server rather than just the last parts of the filenames.
        checksum:       true
        verify_host:    true
    with_items:
        - "ingress-controller-nginx-3.23.0.tgz"  # helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx ; helm pull ingress-nginx/ingress-nginx


-   name:   Install Ingress Controller.
    shell:  |
            PS4="+:\${LINENO}: "
            set -xeu
            helm_name="ingress-controller"
            export KUBECONFIG=/etc/kubernetes/admin.conf
            function act_on_helm_chart {
                set -eu
                local -r action="${1}"
                helm \
                    "${action}" \
                    --create-namespace \
                    --namespace kube-system \
                    "${helm_name}" \
                    "/tmp/artifacts/ingress-controller-nginx-3.23.0.tgz"
            }
            if helm status --namespace kube-system "${helm_name}" \
                | egrep '^STATUS: deployed$'
            then
                h_action=upgrade
            else
                h_action=install
            fi
            if ! act_on_helm_chart "${h_action}" ; then
                helm delete --namespace kube-system "${helm_name}" || true
                act_on_helm_chart install
            fi
    args:
        executable: /bin/bash
    register: fb_ingress_contrller_install

-   name: Install Ingress Controller - feedback
    debug:
        var: "{{ item }}"
    with_items:
        -   fb_ingress_contrller_install.stdout_lines
        -   fb_ingress_contrller_install.stderr_lines
