---

-   name:               HTTPS support for Apt
    apt:
        name:           "{{ deb_pack_list }}"
        state:          absent
    vars:
        deb_pack_list:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common


-   name:               Upload file with Apt public key
    ansible.builtin.copy:
        src:            "{{ item.pub_key.file }}"
        dest:           "/root/{{ item.pub_key.file | basename }}"
        owner: root
        group: root
        mode: '0644'
    with_items:
        - "{{ repos.docker }}"
        - "{{ repos.k8s }}"

-   name:               Insert Apt public key for Docker Apt repo
    apt_key:
        file:           "/root/{{ item.pub_key.file | basename }}"
        state:          present
    with_items:
        - "{{ repos.docker }}"
        - "{{ repos.k8s }}"

-   name:               Add Apt repository
    apt_repository:     # It may not work correctly with older OS
                        # releases. May be better/reliable to upload a
                        # ready for use
                        # '/etc/apt/sources.list.d/docker.list'
                        # from Jinjia template.
        repo:           "{{ item.spec }}"
        state:          present
    with_items:
        - "{{ repos.docker }}"
        - "{{ repos.k8s }}"

-   name:               Drop temporary file
    file:
        path:           "/root/{{ item.pub_key.file | basename }}"
        state:          absent
    with_items:
        - "{{ repos.docker }}"
        - "{{ repos.k8s }}"
