---

#
#  Copyright 2013-2022 ASC
#
#  This file is part of "Οἰκουμένη" ("Ecumene") - set of applications and
#  configurations to assist with deploy and set up of an environments.
#
#  Οἰκουμένη is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation, either version 3 of
#  the License, or (at your option) any later version.
#
#  Οἰκουμένη is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Οἰκουμένη.
#  If not, see <http://www.gnu.org/licenses/>.
#
##


-   name:           Launch permissions configuration upload
    copy:
        src:        _etc_sudoers.d_easy-admin
        dest:       /etc/sudoers.d/easy-admin
        owner:      root
        group:      root
        mode:       0440
        validate:   "visudo -cf %s"


-   name:           Set authorized keys
    authorized_key:
        user:       "{{ ansible_user }}"
        state:      present
        key:        "{{ lookup('file', admin_public_key_file) }}"
